### ISSUE TITLE
老板，这个repo 自动更新包的 action 在哪？

### ISSUE THREAD

**Issue by qingtian110** [sbwml/openwrt_helloworld#3]
一直有 actions-user 这个用户在更新包，但是没有看到 .github 任务流。

是在哪里让它自动更新的？

**Comment by sbwml** [comment]
它在我自建的 git 上update，这里的文件只是和我私有git 的一个 sync

Ps：这里的东西来自helloworld、passwall上游，这个repo 仅自用，请不要在这个地方开任何 issues。请不要在这个山寨来源拉取源码，有问题请直接找对应的上游，谢谢啊

上游：

https://github.com/fw876/helloworld

https://github.com/xiaorouji/openwrt-passwall

从 Windows 版邮件发送

发件人: qingtian110
发送时间: 2024年3月10日 1:45
收件人: sbwml/openwrt_helloworld
抄送: Subscribed
主题: [sbwml/openwrt_helloworld] 老板，这个repo 自动更新包的 action 在哪？ (Issue #3)

一直有 actions-user 这个用户在更新包，但是没有看到 .github 任务流。
是在哪里让它自动更新的？

**Comment by sbwml** [comment]
这种问题如果真的看了 openwrt docs ，如果真的使用翻译看了，如果看了还是没会那就是根本没看完整，如果看完整了问题已经解决。至于docs 链接记得有发过。像这样给了方法不去看，必须要一条条命令，一张张截图贴出来才有可能说的明白的话，挺讨厌的

从 Windows 版邮件发送

发件人: qwerttvv
发送时间: 2024年3月10日 1:59
收件人: sbwml/openwrt_helloworld
抄送: Subscribed
主题: Re: [sbwml/openwrt_helloworld] 老板，这个repo 自动更新包的 action 在哪？ (Issue #3)

咋弄啊，虚心求教下边的5b80c76c55f0d77106faff04056c1568b074491197818375c01a211847296b49怎么算出来的
文档说checkout之后打包tar.xz，然后计算这个包的sha265，但是我怎么弄，也对不上这个值
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://www.github.com/pymumu/smartdns.git
PKG_SOURCE_VERSION:=40dc9eceb78ac558b235a128241b1a4d2819f15f
PKG_MIRROR_HASH:=5b80c76c55f0d77106faff04056c1568b074491197818375c01a211847296b49

**Comment by qingtian110** [comment]
抱歉啊，因为我看 passwall 那些自动化，日常更新后是会出问题的，而你这里的不会，所以现在 follow 你这里的了。

像前两天 chinadns-gn 也是  现在passwall 也是 copy 你这里的来用了。。那里的上游太儿戏了  https://github.com/xiaorouji/openwrt-passwall-packages/commit/f07d0a054bd87811645805342c1a60f9b35e253a

**Comment by qingtian110** [comment]
> > 这种问题如果真的看了 openwrt docs ，如果真的使用翻译看了，如果看了还是没会那就是根本没看完整，如果看完整了问题已经解决。至于docs 链接记得有发过。像这样给了方法不去看，必须要一条条命令，一张张截图贴出来才有可能说的明白的话，挺讨厌的 从 Windows 版邮件发送 发件人: qwerttvv 发送时间: 2024年3月10日 1:59 收件人: sbwml/openwrt_helloworld 抄> 嗐，我真看好几遍都快背下来了，是挺叫人讨厌的……自己都讨厌自己，太废物了啊…我能比医院里流口水的弱智还笨多少呢……

你是真瞎😆  git 协议拉取源码无视 hash，至于makefile 上的值，直接计算DL 缓存的压缩包完事，毕竟git 的hash 只是为了符合包标准

**Comment by qingtian110** [comment]
但是要写自动化计算标准的 git 协议的hash，我也不会。手动的   直接 `sha256sum`   出来的结果直接填写到makefile，无视它到底对不对
